### ISSUE TITLE
Implement 2FA

### ISSUE THREAD

**Issue by eric2905** [schmupu/ioBroker.ring#14]
Please implement the 2FA.

Look here for an sample : https://github.com/dgreif/ring
And here for information about the Ring 2FA : https://github.com/dgreif/ring/wiki/Two-Factor-Auth

Maybe you can use it

**Comment by schmupu** [comment]
Hello Eric,

if you like you can test it the 2FA now. You have to install the ioBroker ring version by GitHub (external link -> dropdown list in ioBroker). 

You have to enter once your ring email and password in the ioBroker ring configuration and activate the checkbox "set two face (once)" and start the adapter. The adapter will get the 2FA refreshtoken and will save the token in the configuration and will delete afterwards the email and password. 

I hope it works?

<img width="1022" alt="Bildschirmfoto 2019-12-29 um 11 09 33" src="https://user-images.githubusercontent.com/38919572/71555384-050eb900-2a2c-11ea-856c-0b3da2a9f752.png">
<img width="1057" alt="Bildschirmfoto 2019-12-29 um 11 10 48" src="https://user-images.githubusercontent.com/38919572/71555385-050eb900-2a2c-11ea-8cee-38f09ba243a7.png">

**Comment by eric2905** [comment]
Hi,

updated to v 1.0.7.
I see the checkbox and checked it, adapter restarts and gives correct info in log (mail date, etc.)
But I don't see a token as in your screenshot.

<img width="1081" alt="ring_2FA-01" src="https://user-images.githubusercontent.com/18639287/71555679-f970c180-2a2e-11ea-85fc-006055e5f27a.png">
![ring_2FA-02](https://user-images.githubusercontent.com/18639287/71555682-fece0c00-2a2e-11ea-8d56-0731c0b9c768.png)

**Comment by schmupu** [comment]
okay, that did not work. could you try following on the shell.

`npx -p ring-client-api ring-auth-cli`

Do you get now a Token? You can copy the token without the " at the beginning and end into ioBroker

**Comment by eric2905** [comment]
That worked, I got a token.
Copied it to the adapter config - works.

Removed adapter and installed it again, tried to use only the adapter config:
Same info in log (worked, removed mail, ...) - but no token in adapter config, checkbox still activated and mail & pwd still filled.
So used the command again and it worked.

But, now I only get my ring doorbell, my other 3 cameras are not listed in objects.
According to the log, only one device is received.

**Comment by HeGa59** [comment]
Hi,
with npx generated token => worked!
Tnx

**Comment by AndyGR42** [comment]
Hi. Can you estimate a GA date for 2FA? Since yesterday, Ring sent me confirmation codes to continue API access even though 2FA is disabled! I decided to disable the instance for the moment.

**Comment by Fragggy** [comment]
Hi, I have a problem, with the command above:

npx -p ring-client-api ring-auth-cli

Gives me an error regarding ffmpeg-for-homebridge

Do I miss something?

--Full Errormesage:

Error: Cannot find module '/root/.npm/_npx/116808/lib/node_modules/ring-client-api/node_modules/ffmpeg-for-homebridge/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Tabrael** [comment]
It works with version  6.1.1

`npx -p ring-client-api@6.1.1 ring-auth-cli `

**Comment by Tabrael** [comment]
Hi,

either ffmpeg-for-homeridge was installed the npx -p ring-client-api ring-auth-cli call is thorwing following error

```
Error: Cannot find module '/root/.npm/_npx/4595/lib/node_modules/ring-client-api                                                             /node_modules/ffmpeg-for-homebridge/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffmpeg-for-homebridge@0.0.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffmpeg-for-homebridge@0.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                             ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-01T18_34_45_798Z-debug.log
Die Installation von ring-client-api@latest ist mit dem Code 1 fehlgeschlagen
```
Greetz Tab

**Comment by schmupu** [comment]
try following:
```
node /opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/ring-auth-cli.js 
```
